name: Repository Automation

on:
  pull_request:
    types:
      - closed

jobs:
  create_artifactory:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Execute Repository Automation Script
        run: |
          INPUTS_FILE="inputs.txt"
          PACKAGE_TYPE=$(grep -o "Package Type: [[:alnum:]]*" "$INPUTS_FILE" | cut -d ' ' -f 3)
          REPO_TYPE=$(grep -m 1 "Type of Repository:" "$INPUTS_FILE" | cut -d ':' -f 2 | tr '[:upper:]' '[:lower:]' | tr -d ' ')

          if [ "$PACKAGE_TYPE" = "helm" ] && [ "$REPO_TYPE" = "local" ]; then
            SCRIPT_PATH="Repo_creation_Scripts/8.sh"
          elif [ "$REPO_TYPE" = "virtual" ]; then
            SCRIPT_PATH="Repo_creation_Scripts/8.1.sh"
          elif [ "$REPO_TYPE" = "local" ] || [ "$REPO_TYPE" = "remote" ]; then
            SCRIPT_PATH="Repo_creation_Scripts/3.8.1.sh"
          else
            echo "No matching condition found for execution."
            exit 1
          fi

          bash "$SCRIPT_PATH" "/$INPUTS_FILE"  # Add a leading slash for the root directory