name: Repository Automation

on:
  pull_request:
    types:
      - closed

jobs:
  create_artifactory:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Execute Repository Automation Script
        run: |
          yaml_file="inputs.yml"
          package_type=$(awk '!/^#/ && /Package Type:/ {sub(/Package Type:/, "", $0); print $0}' "$yaml_file" | tr -d '[:space:]')
          repository_type=$(awk '!/^#/ && /Type of Repository:/ {sub(/Type of Repository:/, "", $0); print $0}' "$yaml_file" | tr -d '[:space:]')

          if [ "$package_type" = "helm" ] && [ "$repository_type" = "local" ]; then
            SCRIPT_PATH="Repo_creation_Scripts/2.helm-local.sh"
          elif [ "$repository_type" = "virtual" ]; then
            SCRIPT_PATH="Repo_creation_Scripts/3.virtual.sh"
          elif [ "$repository_type" = "local" ] || [ "$repository_type" = "remote" ]; then
            SCRIPT_PATH="Repo_creation_Scripts/1.local-remote.sh"
          else
            echo "No matching condition found for execution."
            exit 1
          fi

          bash "$SCRIPT_PATH" "/$yaml_file"  # Add a leading slash for the root directory