name: Repository Automation
on:
  pull_request:
    types:
      - closed
jobs:
  create_artifactory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11  # Choose the Python version you need
      - name: Execute Repository Automation Script
        run: |
          yaml_file="inputs.yml"
          import re
          import os

          with open(yaml_file, 'r') as file:
              yaml_content = file.read()

          package_type = next(re.search(r'Package Type:\s*([^#\n]*)', line).group(1).strip() for line in yaml_content.split('\n') if not line.startswith('#') and 'Package Type:' in line)
          repository_type = next(re.search(r'Type of Repository:\s*([^#\n]*)', line).group(1).strip() for line in yaml_content.split('\n') if not line.startswith('#') and 'Type of Repository:' in line)

          if package_type == "helm" and repository_type == "local":
              script_path = "Repo_creation_Scripts/2.helm-local.py"
          elif repository_type == "virtual":
              script_path = "Repo_creation_Scripts/3.virtual.py"
          elif repository_type == "local" or repository_type == "remote":
              script_path = "Repo_creation_Scripts/1.local-remote.py"
          else:
              print("No matching condition found for execution.")
              exit(1)

          script_path = os.path.join("/", yaml_file, script_path)
          os.system(f"python {script_path}")


