name: Repository Automation

on:
  pull_request:
    types:
      - closed

jobs:
  create_artifactory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Execute Repository Automation Script
        run: |
          PR_TITLE=$(curl -sSL "${{ github.api_url }}/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" | jq -r .title)
          if [[ $PR_TITLE == *"helm"* ]]; then
            SCRIPT_PATH="Repo_creation_Scripts/3.4.sh"
            TEXT_FILE_PATH="inputs.txt"  # Update with the correct file name
            bash "$SCRIPT_PATH" "/$TEXT_FILE_PATH"  # Add a leading slash for the root directory
          else
            echo "PR title does not contain 'helm'. Skipping script execution."
          fi